common_params:
  ros__parameters:
    robot_params:
      wheel:
        radius: 0.0325
        separation_x: 0.129
        separation_y: 0.300 
        vel_tick: 0.229
      accessory:
        neck_default: 330
        grabber_default: 512
mecanumbot_io_node:
  ros__parameters:
    dev_params:
      device_name: "/dev/ttyACM0"
      baudrate: 57600
    packet_params:
      payload_fmt: "<23h14f"
      seq_size: 1
      crc_size: 1
      magic: "55AA" # 0x55, 0xAA
    plausibility_params:
      max_wheel_speed: 10000
      min_pos: -1000
      max_pos: 10000
      max_float_abs: 1e7

mecanumbot_sensorproc_node:
  ros__parameters:
    robot_params:
      battery:
        min_voltage: 9.9
        max_voltage: 12.6
    odom_params:
      frame_id: "odom"
      child_frame_id: "base_footprint"
      from_imu: true
    imu_params:
      frame_id: "imu_link"