std_msgs/Header  header
#goal velocities for wheels  
int cmd_vel_BL  
int cmd_vel_BR 
int cmd_vel_FL 
int cmd_vel_FR
#measured velocities for wheels
int vel_BL  
int vel_BR  
int vel_FL  
int vel_FR  
#measured positions for wheels
int pos_BL  
int pos_BR  
int pos_FL  
int pos_FR  
#measured currents for wheels
int curr_BL  
int curr_BR  
int curr_FL  
int curr_FR  
#measured accelerations for wheels
int acc_BL  
int acc_BR  
int acc_FL  
int acc_FR  
#goal positions for neck and grabbers
int pos_N  
int pos_GL  
int pos_GR  
#sensory data
float voltage  
 #IMU data
float imu_angular_vel_x  
float imu_angular_vel_y  
float imu_angular_vel_z  
float imu_linear_acc_x  
float imu_linear_acc_y  
float imu_linear_acc_z  
float imu_magnetic_x 
float imu_magnetic_y
float imu_magnetic_z
float orientation_w 
float orientation_x 
float orientation_y 
float orientation_z 